[workspace]

members = [
  "lunir"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"

[profile.actions]
inherits = "dev"
opt-level = 0

[profile.actions.package."*"]
opt-level = 0